#
#About: This will install docker
#
---
- hosts: k8s_node
  remote_user: root
  become: yes
  roles:
  - role: flannel
    vars:
      etcd_endpoints: "http://192.168.72.128:2379,http://192.168.72.63:2379,http://192.168.72.157:2379"
      etcd_prefix: /flannel/network
