- name: create user  
  user: uid=27020  name=mongo 
- name: create document 
  file: path=/data/mongo  state=directory owner=mongo group=mongo
- name: provides mongod.conf
  template: src=mongod.conf  dest=/data/mongo/mongod.conf owner=mongo group=mongo
- name: provides mongodb_start.sh
  copy: src=mongodb_start.sh dest=/data/mongo/mongodb_start.sh  owner=mongo group=mongo
